version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.36.19
    - 1.37.1
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.0
