version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
      timezone: America/New_York
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '08:00'
      timezone: America/New_York
