# Encoding: UTF-8
before:
  hooks:
    # - go mod tidy
    # - go generate ./...
builds:
  - env:
    - CGO_ENABLED=0
    # - GOFLAGS=-mod=vendor
    goos:
      - windows
      - linux
      # - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -mod=vendor
    ldflags:
      - -s -w
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.ReleaseVer={{.Version}}
      - -X main.ReleaseDate={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ONLY_BINARY*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

release:
  # disable: true

signs:
  # - artifacts: checksum
  # - artifacts: all
