name: Go
on: [push]
jobs:

  test:
    name: Build
    strategy:
      matrix:
        go: [1.13, 1.14]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Git Info
        id: git
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Test
        env:
          GOFLAGS: '-mod=vendor'
        run: |
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
          go test -v -race $(go list ./... | grep -v /vendor/)

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/') && (matrix.go == 1.14)
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
          # key: ${{ secrets.GPG_CODE_SIGN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
